services:
  traefik-server:
    image: "traefik:2.8.4" 
    command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.swarmMode=true"
        - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
        - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
        - "--certificatesresolvers.mytlschallenge.acme.email=adarsh.singh.legha@gmail.com"
        - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_API_EMAIL=<cf-email>
      - CF_API_KEY=<cf-api-key>
    networks: 
      - traefik-net
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ss-deploy-server:
    image: adeee11/ss-deploy-server:latest
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST_NAME=<host-name>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ss-deploy-server.rule=Host(`api.host-name`)"
      - "traefik.http.routers.ss-deploy-server.entrypoints=websecure"
      - "traefik.http.routers.ss-deploy-server.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.ss-deploy-server.tls=true"
      - "traefik.http.routers.ss-deploy-server.tls.domains[0].main=api.host-name"
      - "traefik.http.routers.ss-deploy-server.tls.domains[0].sans=*.host-name"
      - "traefik.http.services.ss-deploy-server-svc.loadbalancer.server.port=8000"
    networks:
      - traefik-net
    volumes:
      - /srv/app/downloads
      - /srv/app/html
networks:
  traefik-net: 
    external: true